//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapMağazası.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKITAP_MAĞAZASIEntities : DbContext
    {
        public DBKITAP_MAĞAZASIEntities()
            : base("name=DBKITAP_MAĞAZASIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLHAREKET> TBLHAREKET { get; set; }
        public virtual DbSet<TBLKASA> TBLKASA { get; set; }
        public virtual DbSet<TblKategori> TblKategori { get; set; }
        public virtual DbSet<TBLKITAP> TBLKITAP { get; set; }
        public virtual DbSet<TBLPERSONEL> TBLPERSONEL { get; set; }
        public virtual DbSet<TBLUYELER> TBLUYELER { get; set; }
        public virtual DbSet<TBLYAZAR> TBLYAZAR { get; set; }
        public virtual DbSet<TBLHAKIMIZDA> TBLHAKIMIZDA { get; set; }
        public virtual DbSet<TBLILETIŞIM> TBLILETIŞIM { get; set; }
        public virtual DbSet<TBLMESAJLARR> TBLMESAJLARR { get; set; }
        public virtual DbSet<TBLDUYURULAR> TBLDUYURULAR { get; set; }
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
    }
}
