//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapMağazası.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAREKET
    {
        public int ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<byte> PERSONEL { get; set; }
        public Nullable<System.DateTime> ALISTARİH { get; set; }
        public Nullable<System.DateTime> İADETARİH { get; set; }
        public Nullable<bool> ISLEMDURUM { get; set; }
        public Nullable<System.DateTime> UYEGETIRTARIH { get; set; }
    
        public virtual TBLKITAP TBLKITAP { get; set; }
        public virtual TBLUYELER TBLUYELER { get; set; }
    }
}
